### ISSUE TITLE
discourage instanceof

### ISSUE THREAD

**Issue by contra** [gulpjs/gulp-util#104]
Different versions of vinyl should be able to co-exist, since plugins will now be relying on it directly. The README should discourage usage of instanceof

(related: #103)

**Comment by terinjokes** [comment]
I'm partial to `Vinyl.isVinyl` to match `Buffer.isBuffer` and `Array.isArray`.

**Comment by phated** [comment]
:+1: to @terinjokes' idea

**Comment by contra** [comment]
done (0.5.3)
