### ISSUE TITLE
Switch to dateformat-light

### ISSUE THREAD

**Issue by richplastow** [gulpjs/gulp-util#113]
There’s a lightweight alternate to node-dateformat, specially built with gulp-util in mind:
https://www.npmjs.com/package/dateformat-light

See this discussion:
https://github.com/felixge/node-dateformat/issues/36

It will reduce gulp-util’s footprint by 1.8 MB (for 350 files and folders).

**Comment by phated** [comment]
gulp-util is deprecated and won't be receiving any updates other than to print deprecation warnings.  This will be yet another reason for people to stop using the library.
