### ISSUE TITLE
Using gulp-util on black terminals.

### ISSUE THREAD

**Issue by jaysoifer** [gulpjs/gulp-util#114]
Hi,

I'm running gulp-gutil on iterm/oh-my-zsh with a black background and the timestamps are pretty much invisible.

Obviously I can change it back to white but I was wondering if there was any way I could customize the timestamp color the same way we do with the messages.

Thank you very much

**Comment by jonathan-soifer** [comment]
I'm trying to change it directly into Fancy-log but it worked on my custom messages not on the whole plugin. I'm also concerned that this will be overwritten during updates.

**Comment by leegee** [comment]
I also run on a black terminal, and appreciate the way the timestamps are virtually invisible -- they are, to my eye, the least important thing on the screen, and that they are grey helps me focus on the brighter, more relevant messages to their right. 

When I need a timestamp, I make an extra effort to focus, or select with my mouse.

FYI, I have 20% vision with photophobia.

**Comment by phated** [comment]
Closing in favor of https://github.com/gulpjs/gulp-cli/issues/63
