### ISSUE TITLE
Update version of chalk in depedencies

### ISSUE THREAD

**Issue by ccbayer** [gulpjs/gulp-util#120]
i am getting an error in another package (gulp-sass) which is dependent on gulp-util, due to a breaking change from Chalk which has trickled down to this dependency.

I was able to fix by updating my version of Chalk to 1.1.2, instead of 1.0.0 which you have listed here.

if you update your version in the package.json to
```
    "chalk": "^1.1.2"
```
it should fix it.  I tested this in a local project.

see: https://github.com/chalk/chalk/issues/106

**Comment by phated** [comment]
I don't think this is necessary, as the carrot ^ means "get the latest from the 1.x versions; If someone downloaded the broken version, they just need to remove their modules and cache clean.
