### ISSUE TITLE
Using "extname" and other shorthand getters in ".clone()" opts.

### ISSUE THREAD

**Issue by jamen** [gulpjs/gulp-util#122]
Would be handy for quickly changing extension in plugins that compile, or in any case where you just need to change the extension:
```javascript
const html = file.clone({ extname: '.html' });
html.contents = foobar.render(...);
```

**Comment by phated** [comment]
This doesn't belong in the gulp-util repo, as it is related to vinyl;  however, I don't think the clone API would be suitable to overload for this feature.  If you want to open a different issue on https://github.com/gulpjs/vinyl that suggests a new API, we can discuss there.

**Comment by jamen** [comment]
My bad, I opened here because I was using `gutil.replaceExtension(...)`.

**Comment by phated** [comment]
@jamen I'm not sure what version of vinyl added the feature (and it might not be shipping with gulp 3.x), but you can use `file.extension = '.html'` now and it has a setter that handles what `replaceExtension` used to
