### ISSUE TITLE
array-differ dependency does not contain a valid license

### ISSUE THREAD

**Issue by n8rzz** [gulpjs/gulp-util#132]
MIT dictates that the license accompanies all copies of the source code.  the `array-differ@1.0.0` dependency does not include said license.

It looks like the current version of `array-differ` _does_ include it.  

If I get time today I will try and update this myself and open a PR.

**Comment by phated** [comment]
We don't ship the source code for `array-differ`, we provide a manifest of recommended dependencies.  You are the one who installs the source code.  You might want to try to get `array-differ` maintainers to release a 1.0.1 with the license included.

**Comment by n8rzz** [comment]
@phated Yes I understand you don't ship source code, but you do specify versions in the `package.json`.  Thus running `npm install -S gulp-util` gets me `gulp-util` *_and_* all the dependencies listed in `package.json`.  And, since v1.0.0 of `array-differ` is specified in that file, the module that gets downloaded is one without a license.

That is all I'm getting at here.  Since `gulp-util` is a heavily used module, I would assume I'm not the only one who is running into licensing issues.  A license needs to be included with `gulp-util` _and all it's dependencies_.

**Comment by phated** [comment]
@n8rzz that is incorrect. You are responsible for validating any dependencies you install with the `npm install` command.  That is a tool you are choosing to use and could instead install everything manually.  Like I already suggested, you should probably try to get the maintainers of that library to ship a 1.0.1.  I'm locking this.
