### ISSUE TITLE
Doesn't work when on stream with return gulp.src

### ISSUE THREAD

**Issue by MateuszDabrowski** [gulpjs/gulp-util#137]
I created a stream:

`gulp.task('move', function(callback){
  return gulp.src(['./News*/*.html', './News*/**/*.html'])
    .pipe(gulp.dest('Przygotowane/'))
  gutil.log(gutil.colors.bold('Move [Assets] - Done'));
  callback();
});`

However I do not see log. It only shows when I drop return - which I would rather not, as it is required for chaining asynchronous streams.

**Comment by phated** [comment]
This is not a support forum and you are writing JS that doesn't make sense.  Maybe you want to use a linter.
