### ISSUE TITLE
yarn skip to add this dues to non-deterministic behavior

### ISSUE THREAD

**Issue by zymr-keshav** [gulpjs/gulp-util#139]
- macOS 10.12.6
- node -v 6.11.4 ( installed thrugh nvm)
- gulp -v 3.9.1
- yarn -v 1.2.1

when try to add  yarn add gulp-util -D it gives warning in terminal

> warning Pattern ["gulp-util@^3.0.8"] is trying to unpack in the same destination "/Users/keshav.m/Library/Caches/Yarn/v1/npm-gulp-util-3.0.8-0054e1e744502e27c04c187c3ecc505dd54bbb4f" as pattern ["gulp-util@^3.0.0","gulp-util@^3.0.7","gulp-util@^3.0.6","gulp-util@3.0.8","gulp-util@^3.0.8"]. This could result in a non deterministic behavior, skipping.

why is this happening?  even gulp util is working fine but this thing bothers me

**Comment by contra** [comment]
Sounds like a yarn bug, you should open a ticket there.
