### ISSUE TITLE
Dependencies out of date

### ISSUE THREAD

**Issue by rogierschouten** [gulpjs/gulp-util#140]
Some gulp plugins, amongst which gulp-util, are including a very old version of vinyl.  This causes problems  with differently-shaped vinyl objects going through the gulp pipelines.  Please update your vinyl dependency

**Comment by phated** [comment]
@rogierschouten gulp-util has long been soft-deprecated, those modules should update to use vinyl directly.  This module is a gigantic mess that no one needs to download all of and will be hard-deprecated with gulp 4 official release.

**Comment by phated** [comment]
I've deprecated this module on npm so hopefully people start switching off it.
