### ISSUE TITLE
Depricated readme not published?

### ISSUE THREAD

**Issue by BurtHarris** [gulpjs/gulp-util#142]
It seems your intent is to deprecate **gulp-util**.   However, the package listings at https://www.npmjs.com/package/gulp-util and https://yarnpkg.com/en/package/gulp-util don't make this clear, it looks like they don't have the updated README.md.

**Comment by phated** [comment]
@BurtHarris Yep, it sucks that npm sucks :(  Working on a blog post now that will link from the deprecation notice.

**Comment by BurtHarris** [comment]
It looks like you somehow published a version with an unchanged version number.   If you bump it up to 3.0.9 and publish again, I think that will fix it.

**Comment by phated** [comment]
Here it is: https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
