### ISSUE TITLE
The README on npm doesn't have the deprecation note

### ISSUE THREAD

**Issue by joeycozza** [gulpjs/gulp-util#145]
https://www.npmjs.com/package/gulp-util

I wonder if it would be helpful/good to get the README on npm's website up to date with the README on github to explain the deprecation and the alternatives to use.

Just a thought.

**Comment by phated** [comment]
You already get linked to the blog post in the deprecation notice when you install it and I don't want a "new" publish.  Too bad npm never fixed the problem of pushing docs separately from the package.
