### ISSUE TITLE
deprecated gulp-util@3.0.8 used on react-native@0.54.3 > fbjs-scripts@0.8.1

### ISSUE THREAD

**Issue by dwisetiyadi** [gulpjs/gulp-util#148]
deprecated gulp-util@3.0.8 used on react-native@0.54.3 > fbjs-scripts@0.8.1

**Comment by phated** [comment]
I don't think you understand where that should be reported...

**Comment by dwisetiyadi** [comment]
I just the instruction come out on npm install, and that instruction bring me to here.

**Comment by demurgos** [comment]
`gulp-util` is deprecated, _consumers_ must be updated. In this case `fbjs-scripts` was updated (https://github.com/facebook/fbjs/pull/279) but they need to publish their fixed version to npm.
