### ISSUE TITLE
Gulp throws assertion error after fixing gulp-util deprecation with gulp-cli

### ISSUE THREAD

**Issue by codewizard13** [gulpjs/gulp-util#152]
**NOTE:** _This is not a duplicate and this question hasn't already been asked with the details describing my experience, though it is possible, that somewhere in a different ticket, the answer I need already exists. I haven't found it yet, though. Hence, my taking the time to post here_.

## MY ENVIRONMENT ##

* Window 10 64-Bit
* Git Bash
* NodeJS
* Gulp

## THE ISSUE ##

I am not a noob to programming, but _I am a noob to task runners_ like gulp and grunt.

Today I'm following a Lynda.com /LinkedIn Learning tutorial by [Ray Villalobos](https://github.com/planetoftheweb). I'm trying to learn how to work with remote git repositories, and in order to follow along with the tutorial, I am required to install NodeJS and Gulp.

Node installed fine, but Gulp -- which I've never used before -- was giving me a warning about ***gulp-util being deprecated***. The warning points to [this Medium.com post by janiceilene](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5), which seems to be missing detailed implementation instructions for tutorial-following noobs like me.

I'm getting the same error others have been mentioning:

> gulp-util is deprecated - replace it, following the guidelines at  
> https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

### A confusing help message ###

I value and appreciate the work of those involved in producing great open source software, especially since most involved are volunteering their time. Having said that, I'm at a loss as to what I'm supposed to do with this statement from Janice:

> "Open an issue or pull request to remove gulp-util using the following API replacements"

Well I guess here I am opening an issue as instructed, but I don't understand what "_using the following API replacements_" means.

The way it is written, it reads like this:

"_Open an issue telling somebody in support somewhere to connect to my personal computer and remove the deprecated broken version of gulp-util from my personal computer for me, with some kind of configuration substitutions using fat-commas that nobody has explained how to use and have nothing to do with me_."

I see an assortment of key-value pairs, but ***what am I supposed to do with them***? The code I'm trying to execute with gulp is not my own, so I have no idea how or what code might need to be edited. Here is a brief sampling of a few of the key-value pairs:

> gutil.colors => https://www.npmjs.com/package/ansi-colors
> gutil.date => https://www.npmjs.com/package/date-format
> gutil.log => https://www.npmjs.com/package/fancy-log

I'm not sure where to go from here. _I can't finish learning how to work with GitHub because Gulp is broken_.

Perhaps you can understand my frustration and confusion at the unclarity this "help" article has brought. In fact, I suppose I am the ***only one*** to have this problem in understanding as none of the articles I've researched have mentioned or addressed this misunderstanding so far.

## Articles and Posts I've Searched to no avail: ##

* https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
* https://github.com/gulpjs/gulp
* https://github.com/addyosmani/critical/issues/274
* https://groups.google.com/forum/#!topic/cesium-dev/JVeODCDQIvs
* https://mdbootstrap.com/support/gulp-tutorial-major-problem/
* http://keenthemes.com/forums/topic/npm-problem/
* https://github.com/yarnpkg/yarn/issues/2435
* https://stackoverflow.com/questions/49422593/when-i-run-npm-install-in-laravel-project-it-shows-an-error-npm-warn-deprecat

I've just run down a rabbit hole of trying to figure out why I keep getting errors when I type "grunt" in my Git Bash session after having installed it as instructed.

## What I've Tried That Hasn't Worked: ##

I found [this YouTube video](https://www.youtube.com/watch?v=aCV9LR2a0Qo) that gave the following CLI code sequence:

```
npm install gulp-cli -g
npm install gulp -D
touch gulpfile.js
gulp --help
```

Well, I ran all those commands and now I get this error:

```
$ gulp
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\ehw_git_repo\angulardata\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\ehw_git_repo\angulardata\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\ehw_git_repo\angulardata\gulpfile.js:32:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

I've tried to be clear and concise but with enough detail to help highly technical folks empathize with my level of understanding and to see what the issues I am having are. Please let me know if any further clarification is required and I will be more than happy to provide it.

Any help is appreciated.

**Comment by stevelacy** [comment]
1. **Ignore gulp-util warnings** -- those are aimed at plugin developers or users who were _already_ using gulp-util.
2. The error states exactly what the issue is: `AssertionError [ERR_ASSERTION]: Task function must be specified`
  - Tasks are not specified.
  - You need to add a task to the `gulpfile.js`

Just add a task to you `gulpfile.js` such as one of the many in the [Getting started guide](https://github.com/gulpjs/gulp/blob/v3.9.1/docs/getting-started.md)

FYI: That video explains how to setup and run gulp without htting that AssertionError

**Comment by codewizard13** [comment]
Thanks @stevelacy. I'll check out the Getting started guide link and the video.

**Comment by codewizard13** [comment]
@stevelacy I checked out the getting started guide but did not see any video, nor any recipes. Can you clarify were the video and the recipes are?

Now am getting an error:

     Error: Cannot find module 'gulp-util'

If gulp-util is what is giving me the problem, and it is deprecated as referenced above, um ... where do I go from here?

### The Repo I'm Using ###

If it helps to reproduce the error, this is the repository I am using:  https://github.com/planetoftheweb/responsivebootstrap

### Steps to Reproduce ###

NOTE: _I'm using Windows so I'll give the instructions presuming Git Bash and node are installed already._

1. Create a master git folder in root:
    
    `mkdir /c/git_main`
    
2. CD into git_main

    `cd /c/git_main`
    
3. Type `git init` to create the .git hidden folder.

4. Download the responsivebootstrap git repo to local hard drive:

    `git clone https://github.com/planetoftheweb/responsivebootstrap.git`
    
5. CD into new responsivebootstrap folder.

6. Type `git init` and hit enter to initialize the downloaded repo for logging etc.

7. Since gulp 3 has been replaced by a new verson called "***gulp-cli***" remove any previously existing version of gulp:

    `npm rm --global gulp`
    
8. Install the new gulp command line interface globally (meaning you don't have to install it in the root directory. You can install it from anywere and it will be available everywhere:

    `npm install --global gulp-cli`
    
    (_This may be the same as `npm install gulp-cli -g`, but that is unclear_)
    
9. Run `npm install gulp -D` (for some reason), as indicated here: https://gulpjs.com/

![ehscreenshot_2018 05 23_code_gulpjsnpmerrorinstall_01](https://user-images.githubusercontent.com/3443044/40507142-19420df0-5f5d-11e8-8cce-c1a5da649809.jpg)

https://i.imgur.com/kV7DtjP.png

10. Run `touch gulpfile.js`.

11. Run `gulp`.

12. Get **error**:

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\ehw_git_repo\responsivebootstrap\gulpfile.js:2:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

To be clear, I didn't enter any command that had `gulp-util` in the name ... that phrase never came from my fingers.

Thanks again for all your help so far.
