### ISSUE TITLE
Can not install gulp on my project via npm

### ISSUE THREAD

**Issue by amarleku** [gulpjs/gulp-util#167]
Can not install Gulp on my project via NPM on ubuntu I have tried "npm i gulp" and "sudo npm i gulp" but still an error I will show u the error here.

npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ../html/bin/html.js
npm ERR! dest /media/astrit/Local Disc/projects/windows2000css/node_modules/.bin/html
npm ERR! errno -1
npm ERR! Error: EPERM: operation not permitted, symlink '../html/bin/html.js' -> '/media/astrit/Local Disc/projects/windows2000css/node_modules/.bin/html'

**Comment by phated** [comment]
That error has nothing to do with gulp-util. You are trying to link some `html.js` file into your node_modules bin folder.
