### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by skhilliard** [gulpjs/gulp-util#168]
gulp-run has a dependency on gulp-util which references a version of lodash.template that has a critical vulnerability.  Would it be possible to update gulp-run to eliminate this?  I understand that this library is deprecated, but would it be possible to release an emergency patch under these circumstances?

gulp-run > gulp-util > lodash.template
https://github.com/advisories/GHSA-jf85-cpcp-j695

    `-- gulp-run@1.7.1
      +-- gulp-util@3.0.8
      | `-- lodash.template@3.6.2
      `-- lodash.template@4.5.0

**Comment by demurgos** [comment]
I replied to https://github.com/m19c/gulp-run/issues/60.

> `gulp-util` has been deprecated for years and shouldn't even be a dependency.
`gulp-util` will not be updated, use the migration instructions [from the README](https://github.com/gulpjs/gulp-util) to move to a supported dependency.
