### ISSUE TITLE
Real logger

### ISSUE THREAD

**Issue by contra** [gulpjs/gulp-util#33]
- levels
  - errors go to STDERR
- ability to ignore certain things and use globbing (like the `debug` module)
- ability to set a new logger
- time prefix

**Comment by ben-eb** [comment]
+1 for mag/mag-hub. Personally I would prefer if gulp & plugins only log when there is an error, as I'm backgrounding watch tasks most of the time and don't need the hand-holding. Centralised logging with levels would be super sweet. :+1:

**Comment by phated** [comment]
Work being done at https://github.com/gulpjs/gulp-util/pull/105 and the gulplog module

**Comment by phated** [comment]
This has been published in 3.0.7 - sorry for the semver abuse, but we need people to start getting this by default when using the new CLI
