### ISSUE TITLE
Bug: gutil.log() ignores "gulp --silent"

### ISSUE THREAD

**Issue by bid** [gulpjs/gulp-util#68]
See https://github.com/sindresorhus/gulp-imagemin/issues/69

The log() method needs to respect gulps "--silent" argument.

**Comment by stringparser** [comment]
PR or is this stale/not needed anymore? This is would be an easy thing todo if is done globally.

**Comment by contra** [comment]
Not needed anymore since we have a new logger inbound and gulp-util is deprecated

**Comment by stringparser** [comment]
great

**Comment by phated** [comment]
Closing as a duplicate of #33
