### ISSUE TITLE
gulp-util logger - default datetime color

### ISSUE THREAD

**Issue by cidevant** [gulpjs/gulp-util#78]
Its very good, that you can use chalk, to make different colors. But it would be the best, if there could be possibility to change prefixed "datetime" in log module.

I am using osx terminal with theme "Solarized", and datetimes are just invisible. 
![Image of Yaktocat](http://www.imagehosting.cz/images/screensus.png)

Same problem has HTOP (osx), MidnightCommander (osx), but it is quickly fixable.

Thank you!

**Comment by sindresorhus** [comment]
That's a bug in solarized. Every tool shouldn't have to work around it. See the solarized issue tracker for workarounds.
