### ISSUE TITLE
gray is a bad color for timestamps

### ISSUE THREAD

**Issue by AprilArcus** [gulpjs/gulp-util#79]
in `gulp-util/lib/log.js`, line 5:

```javascript
var time = '['+chalk.grey(dateformat(new Date(), 'HH:MM:ss'))+']';
```

this can have a very low-contrast appearance in certain light-on-dark color schemes.

**Comment by sindresorhus** [comment]
We're not going to change just because Solarized is broken. This has been discussed multiple times before.

The real fix is to use a non-broken terminal theme or even one of the Solarized forks which fixes this.
