### ISSUE TITLE
Is gutil.combine deprecated?

### ISSUE THREAD

**Issue by callumacrae** [gulpjs/gulp-util#85]
It seems to be undocumented (and I remember that it used to be), but it doesn't look very deprecated—nothing is saying to not use it, it just isn't documented.

**Comment by sindresorhus** [comment]
Everything is deprecated. Just not officially as not all the things have been extracted out into modules yet.

Just use `multipipe` directly: https://github.com/juliangruber/multipipe

**Comment by callumacrae** [comment]
Fair enough—that makes sense.

How do you separate something like `gutil.log` into a module though? A really really tiny module, or will it be moved into gulp itself?

**Comment by sindresorhus** [comment]
The plan is a better logger. See open issue.
