### ISSUE TITLE
color documentation for .log switched

### ISSUE THREAD

**Issue by Kingdutch** [gulpjs/gulp-util#86]
The README.md says numbers etc. are colored in cyan and strings are colored in magenta. For one this is confusing because .log doesn't auto-color. The second issue is that if you follow this guideline and compare this to the default output from gulp the colors will actually be switched.

tl;dr
numbers are in magenta
strings are in cyan

The docs should note this as a guide, not suggest auto-coloring.

**Comment by contra** [comment]
PR?

**Comment by Kingdutch** [comment]
Pull request made (https://github.com/gulpjs/gulp-util/pull/88)
