### ISSUE TITLE
recursive gutil.template

### ISSUE THREAD

**Issue by sheo13666** [gulpjs/gulp-util#89]
How about make gutil.template - recursive
```javascript
var variables = {
    options: 'folder/<%= subfolder %>/subfolder2',
    subfolder: 'subfolder1'
}

gutil.template('<%= options %>/**/*', variables)
```

**Comment by contra** [comment]
this library is deprecated, no new features sorry

**Comment by sheo13666** [comment]
@contra how library is not deprecated?

**Comment by contra** [comment]
@sheo13666 How is it not deprecated? It is deprecated. We are getting rid of it and asking people not to use it anymore. Use something else.

**Comment by sheo13666** [comment]
@contra sorry bad english, code is planned to be moved to the new version gulp(4)? or planned new library?

**Comment by phated** [comment]
@sheo13666 all functionality will be moved to separate, new libraries.  A lot of the functionality already just points at other modules.  You should use those instead for small dependency trees.
