### ISSUE TITLE
consider externalizing PluginError?

### ISSUE THREAD

**Issue by jonschlinkert** [gulpjs/gulp-util#93]
Would you consider making `PluginError` a module? I have a number of plugins that only use this method, and we also use `PluginError` in non-gulp applications that use vinyl/vinyl-fs.

I just [created a module](https://github.com/jonschlinkert/plugin-error) to do this, but would be happy to transfer to gulpjs and/or do pr to gulp-util to use that module (wherever it lives). fwiw, only formatting changes were made the module I created, no changes to actual behavior - but I'd be happy to make whatever changes are necessary to those as well.

**Comment by phated** [comment]
I believe @contra was working on this at https://github.com/wearefractal/BetterError

**Comment by contra** [comment]
yep ^

**Comment by jonschlinkert** [comment]
nice, that's perfect. thanks
